### ISSUE TITLE
Is the pretrained model the best of the your models?

### ISSUE THREAD

**Issue by JunePark16** [HuangZhiChao95/FewShotMotionTransfer#3]
Thanks for the great work!
Let me ask you one question.
Is the pre-trained model you offered same with the model used for the results shown in the youtube video?

Actually, I used the pretrained model in the repo but my results are not as great as the video as yours
(your video results are strikingly great. But I can not get that great result with the pretrained model)

So I just want to ask you whether I should train a new model with my own data to get better result
or the given pretrained model is good enough to get a better result.

**Comment by HuangZhiChao95** [comment]
I offered the same model used in the paper. 

There may be some distributional shifts between your data and the training data I used like the height of the person and the width of the skeleton. Fine-tuning the model with your own data may be a potential solution.

**Comment by JunePark16** [comment]
Thanks for the reply :)

As for the distributional shifts you mentioned, can I ask you one more question?
Actually,  I am trying to make an animation character move like some other target video (some work out videos). 

In this case, the geometry generator works well but I think the texture generator seems like not working great as the geometry one.

I got some blurred texture for the result video in spite of the fact that the animation character have solid texture. (like solid orange or solid black texture which is quite different from the human videos)

So what do you think? 
Can I get a better result with your pre-trained model for my source dataset (animation video) ?

(FYI, I already fine-tune the model with epochs like 500, 1000, 3000, and more. And the results became better with the more fine-tune epochs. But after some point (3000 for my case), the texture quality is not getting better. So I am confused if I can raise the texture quality)

I attach a frame of my result here. You can see the blurred texture of clothes with no facial expression.

![result](https://user-images.githubusercontent.com/79952376/157567750-f856b082-de84-4de9-809c-6ca45c5a3981.png)

**Comment by HuangZhiChao95** [comment]
Animation character is indeed very different from the real person that I used for training the texture generator. In this case, I think maybe you should train another texture model using animation videos.

**Comment by JunePark16** [comment]
Thanks for your reply!
I really appreciate it  :)
