### ISSUE TITLE
Scripts about generating the keypoint, densepose and foreground segmentation of the human

### ISSUE THREAD

**Issue by WinstonDeng** [HuangZhiChao95/FewShotMotionTransfer#4]
Hi, thanks for your great job!
Could you share the scripts about generating the keypoint, densepose and foreground segmentation of the human?
It could be helpful if you share more guidance about details and data formats.

**Comment by HuangZhiChao95** [comment]
Thanks for your attention to our work. 

The generation of keypoints, densepose needs the package of Openpose and Densepose. They require a lot of dependencies and their installation may vary for different systems.  You may use the docker to install them and it would avoid plenty of dependency issues.

I perform foreground segmentation by the commercial system in Huya. I am not authorized to release it.

The data format of the keypoints follows the format of Openpose. The "image_list.txt" contains only the filename without suffix, i.e. do not include "jpg" or "png" in the image_list.txt. You may find details for data processing in line 86-95 in DataSet.py.

**Comment by WinstonDeng** [comment]
Thanks for your guidance! 
Another request is that, could you share the pre-trained deeplabv3 model for segmentation? Because the download link in Human Segmentation Repo is broken and their authors don't reply.  My email is 842237857@qq.com. Thanks!
