### ISSUE TITLE
Bad results in somewhere

### ISSUE THREAD

**Issue by WinstonDeng** [HuangZhiChao95/FewShotMotionTransfer#5]
Hi, I'm reproducing the result by following your guidance (pretrain->multi-video train->finetune), but the final video shows the unexpected errors.
![image](https://user-images.githubusercontent.com/38663473/204491342-1669f06d-d14a-4561-aed3-4c7607ab0a94.png)
As shown in this figure, the target person performs static pose with bad appearence.
When I run finetune.py by loading your released model without finetune, the result is ok.
![image](https://user-images.githubusercontent.com/38663473/204492312-a52e071c-ac9a-4b58-b83a-9ed706c5dfbd.png)
I try to increase pretrain epochs but still fails. 
Have you ever encountered this problem? How to deal with it?

**Comment by HuangZhiChao95** [comment]
I have not met this problem. Have you pretrained the models with DensePose? What is the results after pretraining?

**Comment by WinstonDeng** [comment]
Hi, the issue is caused by data_split script, and I propose a request [here](https://github.com/HuangZhiChao95/FewShotMotionTransfer/pull/6#issue-1468976234)
